---
name: Bump elastic-stack default version
pipelineid: 'bump-elastic-stack-default-version'

actions:
  default:
    title: '[updatecli] Update default stack version to {{ source "latest8xVersion" }}'
    kind: github/pullrequest
    scmid: default
    spec:
      labels:
        - automation
        - dependency

scms:
  default:
    kind: github
    spec:
      owner: '{{ .scm.owner }}'
      repository: '{{ .scm.repository }}'
      user: '{{ requiredEnv "GITHUB_ACTOR" }}'
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      commitusingapi: true
      branch: main

sources:
  latest8xVersion:
    name: Get latest 8.x version
    kind: file
    transformers:
      # Get only the version to avoid spaces and newlines.
      - findsubmatch:
          pattern: '([0-9\.]+)'
          captureindex: 1
    spec:
      file: https://storage.googleapis.com/artifacts-api/releases/current/8

targets:
  update-default-version:
    name: '[updatecli] Update default stack version to {{ source "latest8xVersion" }}'
    kind: file
    sourceid: latest8xVersion
    scmid: default
    spec:
      file: internal/install/stack_version.go
      matchpattern: '(DefaultStackVersion =) "[^"]+"'
      replacepattern: '$1 "{{ source "latest8xVersion" }}"'
