ARG ES_AGENT_IMAGE=docker.elastic.co/elastic-agent/elastic-agent-complete:latest
FROM $ES_AGENT_IMAGE

{{ $pre_start_script := fact "pre_start_script" }}
{{ $custom_script_filename := fact "custom_script_filename" }}
{{ $custom_script := fact "custom_script" }}
{{ $entrypoint_script_filename := fact "entrypoint_script_filename" }}

{{ $entrypoint_path := "/usr/local/bin/custom-entrypoint.sh" }}

USER root

{{ if ne $custom_script "" }}
COPY {{ $custom_script_filename}} .
RUN chmod u+x {{ $custom_script_filename }} && ./{{ $custom_script_filename }}
{{ end }}

{{ if ne $pre_start_script "" }}
COPY {{ $entrypoint_script_filename }} {{ $entrypoint_path }}
RUN chmod a+x {{ $entrypoint_path }}
{{ end }}

USER elastic-agent

{{ if ne $pre_start_script "" }}
ENTRYPOINT ["{{ $entrypoint_path }}"]
CMD [""]
{{ end }}
