version: "2"

run:
  timeout: 5m

linters:
  default: standard
  disable:
    - errcheck # TODO: Fix these errors and enable it.
  enable:
    - forbidigo
    - staticcheck
  settings:
    staticcheck:
      checks:
        - "SA*"  # Only SA checks, matching original staticcheck default behavior
    forbidigo:
      forbid:
        - pattern: ^os\.Getwd$
          msg: "Please don't rely on current path in subcommands"
        - pattern: ^os\.Chdir$
          msg: "Please use absolute paths in subcommands"
        - pattern: ^filepath\.Abs$
          msg: "filepath.Abs relies on the current working path, what is not allowed in subcommands"
      analyze-types: true
      exclude-godoc-examples: true
  exclusions:
    rules:
      # Exclude forbidigo from test files (matches original -tests=false behavior)
      - linters:
          - forbidigo
        path: _test\.go$
