queue_rules:
  - name: default
    conditions:
      - check-success=buildkite/elastic-package

pull_request_rules:
  - name: automatic approval for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot
  - name: automatic merge of bot 🤖
    conditions:
      - check-success=buildkite/elastic-package
      - check-success=CLA
      - base=main
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      queue:
        method: squash
        name: default
