queue_rules:
  - name: default
    queue_conditions:
      - check-success=buildkite/elastic-package
      - check-success=CLA
      - base=main
      - author~=^dependabot(|-preview)\[bot\]$
    merge_conditions:
      - check-success=buildkite/elastic-package
    merge_method: squash

pull_request_rules:
  - name: automatic approval for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot
  - name: automatic merge of bot 🤖
    conditions: []
    actions:
      queue:
        name: default
