FROM {{ fact "registry_base_image" }}

ARG PROFILE

# Disable package validation (already done).
ENV EPR_DISABLE_PACKAGE_VALIDATION=true

ENV EPR_FEATURE_PROXY_MODE=true
ENV EPR_PROXY_TO={{ fact "epr_proxy_to" }}

COPY profiles/${PROFILE}/stack/package-registry.yml /package-registry/config.yml
COPY stack/development/ /packages/development
