ARG IMAGE
FROM ${IMAGE}

RUN bin/logstash-plugin install logstash-filter-elastic_integration

# Copying the file here instead of using a volume so it can be modified and reload
# automatically.
COPY --chown=logstash:root ./logstash.conf /usr/share/logstash/pipeline/logstash.conf

CMD bin/logstash -f /usr/share/logstash/pipeline/logstash.conf --config.reload.automatic
