version: "2.3"
services:
  docker-custom-agent:
    image: "${ELASTIC_AGENT_IMAGE_REF}"
    healthcheck:
      test: "elastic-agent status"
      retries: 180
      interval: 1s
    hostname: docker-custom-agent
    environment:
      - FLEET_ENROLL=1
      - FLEET_INSECURE=1
      - FLEET_URL=http://fleet-server:8220
    volumes:
      - ${SERVICE_LOGS_DIR}:/tmp/service_logs/
