version: '2.3'
services:
  terraform:
    build: .
    tty: true
    stop_grace_period: 5m
    environment:
      - TF_VAR_TEST_RUN_ID=${TF_VAR_TEST_RUN_ID:-detached}
      - TF_VAR_REPO_NAME=${REPO_NAME:-unknown}
      - TF_VAR_PULL_REQUEST=pr-${CHANGE_ID:-unknown}
      - TF_VAR_CI_BUILD_NUMBER=${BUILD_NUMBER:-unknown}
    volumes:
      - ${TF_DIR}:/stage
