version: '2.3'
services:
  terraform:
    build: .
    tty: true
    stop_grace_period: 5m
    environment:
      - TF_VAR_TEST_RUN_ID=${TF_VAR_TEST_RUN_ID:-detached}
      - TF_VAR_CREATED_DATE=${TF_VAR_CREATED_DATE:-unknown}
      - TF_VAR_BRANCH_NAME=${BRANCH_NAME:-unknown}
      - TF_VAR_BUILD_ID=${BUILD_ID:-unknown}
      - TF_VAR_ENVIRONMENT=${TF_VAR_ENVIRONMENT:-unknown}
      - TF_VAR_OWNER=${TF_VAR_OWNER:-unknown}
    volumes:
      - ${TF_DIR}:/stage
