services:
  docker-custom-agent:
    image: "${ELASTIC_AGENT_IMAGE_REF}"
    healthcheck:
      test: "elastic-agent status"
      retries: 180
      interval: 1s
    hostname: docker-custom-agent
    cap_add:
      - CAP_CHOWN
    cap_drop:
      - ALL
    environment:
      - FLEET_ENROLL=1
      - FLEET_URL=https://fleet-server:8220
      - KIBANA_HOST=https://kibana:5601
      - FLEET_TOKEN_POLICY_NAME=${FLEET_TOKEN_POLICY_NAME}
    volumes:
      - ${SERVICE_LOGS_DIR}:/tmp/service_logs/
      - ${LOCAL_CA_CERT}:/etc/ssl/certs/elastic-package.pem
