FROM --platform=linux/amd64 ubuntu:24.04
ENV GCLOUD_CLI_VERSION=583.0.0-0
ENV TERRAFORM_VERSION=1.16.1-1

RUN apt-get -qq update \
  && apt-get install -yq curl apt-transport-https ca-certificates gnupg \
  && apt-get clean

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee /etc/apt/sources.list.d/google-cloud-cli.list \
  && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg \
  && apt-get update -qq \
  && apt-get install google-cloud-cli=${GCLOUD_CLI_VERSION} -yq \
  && apt-get clean

RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg \
  && echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com noble main" | tee /etc/apt/sources.list.d/hashicorp.list \
  && apt-get update -qq \
  && apt-get install -yq terraform=${TERRAFORM_VERSION} \
  && apt-get clean

HEALTHCHECK --timeout=3s CMD sh -c "[ -f /tmp/tf-applied ]"

ENV TF_IN_AUTOMATION=true
ENV TF_CLI_ARGS="-no-color"
ADD run.sh /
RUN chmod +x /run.sh
WORKDIR /workspace

ENTRYPOINT exec /run.sh
