version: '2.3'
services:
  terraform:
    build: .
    tty: true
    stop_grace_period: 5m
    environment:
      - TF_VAR_TEST_RUN_ID=${TF_VAR_TEST_RUN_ID:-detached}
      - TF_VAR_CREATED_DATE=${CREATED_DATE:-unknown}
      - TF_VAR_BRANCH=${BRANCH_NAME_LOWER_CASE:-unknown}
      - TF_VAR_BUILD_ID=${BUILD_ID:-unknown}
      - TF_VAR_ENVIRONMENT=${ENVIRONMENT:-unknown}
      - TF_VAR_REPO=${REPO:-unknown}
    volumes:
      - ${TF_DIR}:/stage
      - ${TF_OUTPUT_DIR}:/output
