env:
  SETUP_GVM_VERSION: 'v0.5.2' # https://github.com/andrewkroh/gvm/issues/44#issuecomment-1013231151
  DOCKER_COMPOSE_VERSION: "v2.24.1"
  DOCKER_VERSION: "26.1.2"
  KIND_VERSION: 'v0.27.0'
  K8S_VERSION: 'v1.32.0'
  YQ_VERSION: 'v4.44.3'

  # Agent images used in pipeline steps
  LINUX_GOLANG_AGENT_IMAGE: "golang:${GO_VERSION}"
  UBUNTU_X86_64_AGENT_IMAGE: "family/core-ubuntu-2204"
  MACOS_ARM_AGENT_IMAGE: "generic-13-ventura-arm"
  # Using this one instead of family/core-windows-2022 because of conflicts with the pre-installed docker.
  WINDOWS_AGENT_IMAGE: "family/platform-ingest-beats-windows-2022"

  # Elastic package settings
  # Manage docker output/logs
  ELASTIC_PACKAGE_COMPOSE_DISABLE_VERBOSE_OUTPUT: "true"
  # Set maximum number of parallel tests to run if package allows it
  ELASTIC_PACKAGE_MAXIMUM_NUMBER_PARALLEL_TESTS: 3
  # Enable/Disable the usage of wolfi images for Elastic Agent
  ELASTIC_PACKAGE_DISABLE_ELASTIC_AGENT_WOLFI: "${ELASTIC_PACKAGE_DISABLE_ELASTIC_AGENT_WOLFI:-false}"


steps:

  - label: ":elastic:  tests"
    command: ".buildkite/scripts/test-oidc.sh"
    agents:
      provider: "gcp"
      image: "${UBUNTU_X86_64_AGENT_IMAGE}"
    env:
    plugins:
      - elastic/oblt-google-auth#v1.2.0:
          lifetime: 3600 # seconds
          project-id: "elastic-observability-ci"
          project-number: "911195782929"
