env:
  SETUP_GVM_VERSION: 'v0.6.0' # https://github.com/andrewkroh/gvm/issues/44#issuecomment-1013231151
  GH_CLI_VERSION: "2.29.0"
  JQ_VERSION: "1.7"
  # Agent images used in pipeline steps
  LINUX_GOLANG_AGENT_IMAGE: "golang:${GO_VERSION}"

steps:
  - label: ":go: Run check-static"
    key: check-static
    command: "make check-static"
    agents:
      image: "${LINUX_GOLANG_AGENT_IMAGE}"
      cpu: "8"
      memory: "4G"
  - label: ":go: :linux: Run unit tests"
    key: unit-tests-linux
    command: "make test-go-ci"
    artifact_paths:
      - "build/test-results/*.xml"
      - "build/test-coverage/*.xml"
    agents:
      image: "${LINUX_GOLANG_AGENT_IMAGE}"
      cpu: "8"
      memory: "4G"
  - label: ":hammer: Create PR in integrations"
    key: pr-integrations
    command: ".buildkite/scripts/test-with-integrations.sh"
    env:
      GITHUB_EMAIL: "elasticmachine@elastic.co"
      GITHUB_USERNAME: "elastic-vault-github-plugin-prod"
    plugins:
      # Required to push branches, create PRs and post comments on PRs
      - elastic/vault-github-token#v0.1.0:
    agents:
      provider: "gcp"
    depends_on:
      - check-static
      - unit-tests-linux

