env:
  SETUP_GVM_VERSION: 'v0.5.0' # https://github.com/andrewkroh/gvm/issues/44#issuecomment-1013231151
  GOLANG_VERSION: "1.20.3"
  GH_CLI_VERSION: "2.29.0"
  JQ_VERSION: "1.6"

steps:
  - label: ":go: Run check-static"
    key: check-static
    command: "make check-static"
    agents:
      image: "golang:${GOLANG_VERSION}"
      cpu: "8"
      memory: "4G"
  - label: ":go: :linux: Run unit tests"
    key: unit-tests-linux
    command: "make test-go-ci"
    artifact_paths:
      - "build/test-results/*.xml"
      - "build/test-coverage/*.xml"
    agents:
      image: "golang:${GOLANG_VERSION}"
      cpu: "8"
      memory: "4G"
  - label: ":hammer: Create PR in integrations"
    key: pr-integrations
    command: ".buildkite/scripts/test-with-integrations.sh"
    agents:
      provider: "gcp"
    depends_on:
      - check-static
      - unit-tests-linux

