agents:
  image: "golang:1.19.5"
  cpu: "8"
  memory: "4G"


steps:
  - label: ":go: Run check-static"
    command: "make check-static"
  - label: ":go: Run unit tests"
    command: "make test-go-ci"
    artifact_paths:
      - "build/test-results/*.xml"

  - wait

  - plugins:
      - junit-annotate#v2.4.1:
          artifacts: "build/test-results/*.xml"

