env:
  GOLANG_VERSION: "1.20.3"

steps:
  - label: ":go: Run check-static"
    key: check-static
    command: "make check-static"
    agents:
      image: "golang:${GOLANG_VERSION}"
      cpu: "8"
      memory: "4G"

