steps:
  - label: "Example Test"
    command: echo "Hello!"

  - label: ":go: Build package"
    key: build-package
    command:
      - "make install"
      - "cd test/packages/package-storage/package_storage_candidate; elastic-package build -v --zip"
    agents:
      image: "golang:1.19.5"
      cpu: "8"
      memory: "4G"

  - label: "Test"
    key: sign-publish
    command: ".buildkite/scripts/signAndPublishPackage.sh"
    agents:
      provider: "gcp"
