env:
  SETUP_GVM_VERSION: 'v0.5.1' # https://github.com/andrewkroh/gvm/issues/44#issuecomment-1013231151
  LINUX_AGENT_IMAGE: "golang:${GO_VERSION}"

steps:
  - label: ":go: Build package"
    key: build-package
    command:
      - "make install"
      - "cd test/packages/package-storage/package_storage_candidate; elastic-package build -v --zip"
    agents:
      image: "${LINUX_AGENT_IMAGE}"
      cpu: "8"
      memory: "4G"
    artifact_paths:
      - build/packages/*.zip

  - label: "Sign and Publish package"
    key: sign-publish
    command: ".buildkite/scripts/signAndPublishPackage.sh"
    depends_on:
      - build-package
    timeout_in_minutes: 90
    agents:
      provider: "gcp"
      image: family/core-ubuntu-2004
