// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

package docs

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/pmezard/go-difflib/difflib"

	"github.com/elastic/elastic-package/internal/packages"
)

// Composable packages bundle the fields and the input documentation of the packages they
// require at build time, so {{ fields }} and {{ inputDocs }} can only be fully rendered from
// a built package. When linting from the source tree, these regions are rendered as
// bundledSentinel and matched against the committed readme ignoring their content.

const (
	// bundledSentinel stands for the content generated from the bundled input packages
	// when rendering a composable readme without a built package.
	bundledSentinel = "\x00elastic-package-bundled\x00"
	// bundledPlaceholder replaces the bundled regions in the diffs shown to the user.
	bundledPlaceholder = "<content generated from the required input packages>"
)

// matchesBundledRegions matches the existing readme against the segments of a readme
// rendered with a sentinel in place of each bundled region: the existing content must start
// with the first segment, end with the last one and contain the rest in order, with
// anything in between.
func matchesBundledRegions(existing string, segments []string) bool {
	if len(segments) == 1 {
		return existing == segments[0]
	}

	if !strings.HasPrefix(existing, segments[0]) {
		return false
	}
	rest := existing[len(segments[0]):]
	for _, segment := range segments[1 : len(segments)-1] {
		idx := strings.Index(rest, segment)
		if idx < 0 {
			return false
		}
		rest = rest[idx+len(segment):]
	}
	return strings.HasSuffix(rest, segments[len(segments)-1])
}

// collapseBundledRegions replaces, in the existing readme, the lines that the line diff
// against the wanted readme (with bundledPlaceholder in the bundled regions) pairs only with
// a placeholder, so that diffs don't show the content of the bundled regions.
func collapseBundledRegions(existing, want string) string {
	existingLines := difflib.SplitLines(existing)
	wantLines := difflib.SplitLines(want)

	var collapsed []string
	for _, op := range difflib.NewMatcher(existingLines, wantLines).GetOpCodes() {
		switch {
		case op.Tag == 'e':
			collapsed = append(collapsed, existingLines[op.I1:op.I2]...)
		case op.Tag == 'r' && isBundledPlaceholder(wantLines[op.J1:op.J2]):
			collapsed = append(collapsed, wantLines[op.J1:op.J2]...)
		case op.Tag != 'i':
			collapsed = append(collapsed, existingLines[op.I1:op.I2]...)
		}
	}
	// difflib.SplitLines terminates every line, including the last one, with a new line.
	return strings.TrimSuffix(strings.Join(collapsed, ""), "\n")
}

func isBundledPlaceholder(lines []string) bool {
	found := false
	for _, line := range lines {
		switch {
		case strings.Contains(line, bundledPlaceholder):
			found = true
		case strings.TrimSpace(line) != "":
			return false
		}
	}
	return found
}

// hasRequiredInputs reports whether the package at packageRoot is a composable integration,
// i.e. type == "integration" with at least one requires.input entry.
func hasRequiredInputs(packageRoot string) (bool, error) {
	m, err := packages.ReadPackageManifestFromPackageRoot(packageRoot)
	if err != nil {
		return false, fmt.Errorf("reading package manifest: %w", err)
	}
	return m.Type == "integration" && m.Requires != nil && len(m.Requires.Input) > 0, nil
}

// ReadmeSnapshot holds the committed readme files of a composable package, to be compared
// with the ones regenerated by the build.
type ReadmeSnapshot struct {
	packageRoot string
	// files maps the readme file names to their committed content, nil if they don't exist.
	files map[string][]byte
}

// SnapshotComposableReadmes reads the committed readme files that are generated from a
// template in a composable package. It returns nil for other packages.
func SnapshotComposableReadmes(packageRoot string) (*ReadmeSnapshot, error) {
	composable, err := hasRequiredInputs(packageRoot)
	if err != nil {
		return nil, fmt.Errorf("checking required inputs failed: %w", err)
	}
	if !composable {
		return nil, nil
	}

	templates, err := filepath.Glob(filepath.Join(packageRoot, "_dev", "build", "docs", "*.md"))
	if err != nil {
		return nil, fmt.Errorf("reading directory entries failed: %w", err)
	}

	snapshot := &ReadmeSnapshot{packageRoot: packageRoot, files: make(map[string][]byte)}
	for _, template := range templates {
		fileName := filepath.Base(template)
		existing, found, err := readReadme(fileName, packageRoot)
		if err != nil {
			return nil, fmt.Errorf("reading README file failed: %w", err)
		}
		if !found {
			existing = nil
		}
		snapshot.files[fileName] = existing
	}
	return snapshot, nil
}

// VerifyUnchanged returns an error with the differences if any of the readme files was
// regenerated with a different content, or didn't exist, since the snapshot was taken.
// It is meant to be used after the package is built, followed by Restore if it fails, so the
// check doesn't pass when it is run again without regenerating the readme files with the build.
func (s *ReadmeSnapshot) VerifyUnchanged() error {
	if s == nil {
		return nil
	}

	var outdated []string
	for fileName, committed := range s.files {
		current, found, err := readReadme(fileName, s.packageRoot)
		if err != nil {
			return fmt.Errorf("reading README file failed: %w", err)
		}
		if !found {
			continue // not rendered, e.g. because the template is not used.
		}
		if committed != nil && bytes.Equal(committed, current) {
			continue
		}
		diff, err := readmeDiff(string(committed), string(current))
		if err != nil {
			return fmt.Errorf("comparing README file failed: %w", err)
		}
		outdated = append(outdated, fmt.Sprintf("%s:\n%s", fileName, diff))
	}
	if len(outdated) == 0 {
		return nil
	}
	sort.Strings(outdated)
	return fmt.Errorf("the README files are out of date, run \"elastic-package build\" to regenerate them and commit the changes:\n%s", strings.Join(outdated, "\n"))
}

// Restore writes back the committed readme files, removing the ones that didn't exist.
// It is meant to be used when the check fails, as the build may have regenerated the readme files.
func (s *ReadmeSnapshot) Restore() error {
	if s == nil {
		return nil
	}
	for fileName, committed := range s.files {
		err := s.restore(fileName, committed)
		if err != nil {
			return fmt.Errorf("restoring README file failed: %w", err)
		}
	}
	return nil
}

// restore writes back the committed content of a readme file, or removes it if it didn't exist.
func (s *ReadmeSnapshot) restore(fileName string, committed []byte) error {
	path := readmePath(fileName, s.packageRoot)
	if committed == nil {
		err := os.Remove(path)
		if err != nil && !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("removing file failed (path: %s): %w", path, err)
		}
		return nil
	}
	err := os.WriteFile(path, committed, 0o644)
	if err != nil {
		return fmt.Errorf("writing file failed (path: %s): %w", path, err)
	}
	return nil
}
