// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

package docs

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/pmezard/go-difflib/difflib"

	"github.com/elastic/elastic-package/internal/fields"
	"github.com/elastic/elastic-package/internal/logger"
	"github.com/elastic/elastic-package/internal/packages"
)

// ReadmeFile contains file name and status of each readme file.
type ReadmeFile struct {
	FileName string
	UpToDate bool
	Diff     string
	Error    error
}

const (
	doNotModifyStr string = `<!-- NOTICE: Do not edit this file manually.-->
<!-- This file is automatically generated by Elastic Package -->`
)

// AreReadmesUpToDate function checks if all the .md readme files are up-to-date.
func AreReadmesUpToDate(repositoryRoot *os.Root, packageRoot string, schemaURLs fields.SchemaURLs) ([]ReadmeFile, error) {
	linksFilePath, err := linksDefinitionsFilePath(repositoryRoot)
	if err != nil {
		return nil, fmt.Errorf("locating links file failed: %w", err)
	}

	files, err := filepath.Glob(filepath.Join(packageRoot, "_dev", "build", "docs", "*.md"))
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return nil, fmt.Errorf("reading directory entries failed: %w", err)
	}

	var readmeFiles []ReadmeFile
	for _, filePath := range files {
		fileName := filepath.Base(filePath)
		ok, diff, err := isReadmeUpToDate(repositoryRoot, fileName, linksFilePath, packageRoot, schemaURLs)
		if !ok || err != nil {
			readmeFile := ReadmeFile{
				FileName: fileName,
				UpToDate: ok,
				Diff:     diff,
				Error:    err,
			}
			readmeFiles = append(readmeFiles, readmeFile)
		}
	}

	if readmeFiles != nil {
		return readmeFiles, fmt.Errorf("files do not match")
	}
	return readmeFiles, nil
}

// isReadmeUpToDate function checks if a single readme file is up-to-date.
// For composable packages the content generated by {{ fields }} and {{ inputDocs }}
// depends on the input packages bundled at build time, so it can't be verified here:
// only the rest of the readme is compared and the bundled regions match anything.
func isReadmeUpToDate(repositoryRoot *os.Root, fileName, linksFilePath, packageRoot string, schemaURLs fields.SchemaURLs) (bool, string, error) {
	logger.Debugf("Check if %s is up-to-date", fileName)

	// the readme is generated within the package root, so source should be the packageRoot files too
	rendered, shouldBeRendered, err := generateReadme(repositoryRoot, fileName, linksFilePath, packageRoot, "", true, schemaURLs)
	if err != nil {
		return false, "", fmt.Errorf("generating readme file failed: %w", err)
	}
	if !shouldBeRendered {
		return true, "", nil // README file is static and doesn't use template.
	}

	segments := strings.Split(string(rendered), bundledSentinel)
	if len(segments) > 1 {
		logger.Warnf("%s: the sections generated from the required input packages ({{ fields }}, {{ inputDocs }}) can't be verified by lint, "+
			"run 'elastic-package check' or 'elastic-package build' to verify them against the bundled README", fileName)
	}

	existing, found, err := readReadme(fileName, packageRoot)
	if err != nil {
		return false, "", fmt.Errorf("reading README file failed: %w", err)
	}
	if !found {
		return false, "", nil
	}

	if matchesBundledRegions(string(existing), segments) {
		return true, "", nil
	}
	want := strings.Join(segments, bundledPlaceholder)
	diff, err := readmeDiff(collapseBundledRegions(string(existing), want), want)
	return false, diff, err
}

func readmeDiff(existing, rendered string) (string, error) {
	var buf bytes.Buffer
	err := difflib.WriteUnifiedDiff(&buf, difflib.UnifiedDiff{
		A:        difflib.SplitLines(existing),
		B:        difflib.SplitLines(rendered),
		FromFile: "want",
		ToFile:   "got",
		Context:  1,
	})
	return buf.String(), err
}

// UpdateReadmes function updates all .md readme files using a defined template
// files. The function doesn't perform any action if the template file is not present.
// For composable packages, whose readme depends on the bundled input packages, the readme
// is regenerated as usual but an error is returned if the committed one was out of date,
// so that the pending changes are not missed.
func UpdateReadmes(repositoryRoot *os.Root, packageRoot, buildPackageRoot string, schemaURLs fields.SchemaURLs) error {
	linksFilePath, err := linksDefinitionsFilePath(repositoryRoot)
	if err != nil {
		return fmt.Errorf("locating links file failed: %w", err)
	}

	readmeFiles, err := filepath.Glob(filepath.Join(packageRoot, "_dev", "build", "docs", "*.md"))
	if err != nil {
		return fmt.Errorf("reading directory entries failed: %w", err)
	}

	var outdated []string
	for _, filePath := range readmeFiles {
		fileName := filepath.Base(filePath)
		target, diff, err := updateReadme(repositoryRoot, fileName, linksFilePath, packageRoot, buildPackageRoot, schemaURLs)
		if err != nil {
			return fmt.Errorf("updating readme file %s failed: %w", fileName, err)
		}

		// Log only when a file has been rendered/updated.
		if target != "" {
			fileName := filepath.Base(target)
			fmt.Printf("%s file rendered: %s\n", fileName, target)
		}
		if diff != "" {
			outdated = append(outdated, fmt.Sprintf("%s:\n%s", fileName, diff))
		}
	}
	if len(outdated) > 0 {
		return fmt.Errorf("readme files were out of date and have been regenerated, review and commit the changes:\n%s", strings.Join(outdated, "\n"))
	}
	return nil
}

// updateReadme function updates a single readme file using a defined template file.
// It writes the rendered file to both the package directory and the package build directory.
// For composable packages it also returns the diff between the committed readme and the
// rendered one, if they differ or the committed readme doesn't exist.
func updateReadme(repositoryRoot *os.Root, fileName, linksFilePath, packageRoot, buildPackageRoot string, schemaURLs fields.SchemaURLs) (string, string, error) {
	logger.Debugf("Update the %s file", fileName)

	rendered, shouldBeRendered, err := GenerateReadme(repositoryRoot, fileName, linksFilePath, packageRoot, buildPackageRoot, schemaURLs)
	if err != nil {
		return "", "", err
	}
	if !shouldBeRendered {
		return "", "", nil
	}

	var diff string
	composable, err := hasRequiredInputs(packageRoot)
	if err != nil {
		return "", "", fmt.Errorf("checking required inputs failed: %w", err)
	}
	if composable {
		existing, _, err := readReadme(fileName, packageRoot)
		if err != nil {
			return "", "", fmt.Errorf("reading README file failed: %w", err)
		}
		if !bytes.Equal(existing, rendered) {
			diff, err = readmeDiff(string(existing), string(rendered))
			if err != nil {
				return "", "", fmt.Errorf("comparing README file failed: %w", err)
			}
		}
	}

	target, err := writeReadme(fileName, packageRoot, rendered)
	if err != nil {
		return "", "", fmt.Errorf("writing %s file failed: %w", fileName, err)
	}

	_, err = writeReadme(fileName, buildPackageRoot, rendered)
	if err != nil {
		return "", "", fmt.Errorf("writing %s file failed: %w", fileName, err)
	}
	return target, diff, nil
}

// GenerateReadme generates the readme file content.
// The template lives under _dev/build/docs in packageRoot.
// For composable packages (those with requires.input), pass buildPackageRoot so that
// {{ inputDocs }} and {{ fields }} read from the bundled build output instead of the source tree.
// Pass "" for buildPackageRoot to always render from source (e.g. in preview): the bundled
// content is then missing, since it only exists in the built package.
func GenerateReadme(repositoryRoot *os.Root, fileName, linksFilePath, packageRoot, buildPackageRoot string, schemaURLs fields.SchemaURLs) ([]byte, bool, error) {
	return generateReadme(repositoryRoot, fileName, linksFilePath, packageRoot, buildPackageRoot, false, schemaURLs)
}

// generateReadme implements GenerateReadme. When maskBundled is set, the output of the
// {{ fields }} and {{ inputDocs }} functions of composable packages is replaced by bundledSentinel.
func generateReadme(repositoryRoot *os.Root, fileName, linksFilePath, packageRoot, buildPackageRoot string, maskBundled bool, schemaURLs fields.SchemaURLs) ([]byte, bool, error) {
	logger.Debugf("Generate %s file (package: %s)", fileName, packageRoot)
	templatePath, found, err := findReadmeTemplatePath(fileName, packageRoot)
	if err != nil {
		return nil, false, fmt.Errorf("can't locate %s template file: %w", fileName, err)
	}
	if !found {
		logger.Debug("README file is static, can't be generated from the template file")
		return nil, false, nil
	}
	logger.Debugf("Template file for %s found: %s", fileName, templatePath)

	linksMap, err := readLinksMap(linksFilePath)
	if err != nil {
		return nil, false, err
	}

	rendered, err := renderReadmeTemplate(repositoryRoot, fileName, packageRoot, buildPackageRoot, templatePath, maskBundled, linksMap, schemaURLs)
	if err != nil {
		return nil, true, fmt.Errorf("rendering Readme failed: %w", err)
	}
	return rendered, true, nil
}

// findReadmeTemplatePath function looks for the README template file in the _dev/build/docs directory.
func findReadmeTemplatePath(fileName, packageRoot string) (string, bool, error) {
	templatePath := filepath.Join(packageRoot, "_dev", "build", "docs", fileName)
	_, err := os.Stat(templatePath)
	if err != nil && errors.Is(err, os.ErrNotExist) {
		return "", false, nil // README.md file not found
	}
	if err != nil {
		return "", false, fmt.Errorf("can't stat the %s file: %w", fileName, err)
	}
	return templatePath, true, nil
}

// renderReadme renders the readme template.
// packageRoot is always the source package directory; it is used for all functions except
// inputDocs and fields, which switch to buildPackageRoot for composable packages so that
// bundled content (resolved input types, merged field definitions) is included.
// Pass "" for buildPackageRoot to always render from source.
// Lint doesn't use this function, see isReadmeUpToDate.
func renderReadme(repositoryRoot *os.Root, fileName, packageRoot, buildPackageRoot, templatePath string, linksMap linkMap, schemaURLs fields.SchemaURLs) ([]byte, error) {
	return renderReadmeTemplate(repositoryRoot, fileName, packageRoot, buildPackageRoot, templatePath, false, linksMap, schemaURLs)
}

// renderReadmeTemplate implements renderReadme. When maskBundled is set and the package
// is composable, {{ fields }} and {{ inputDocs }} render bundledSentinel instead of reading data.
func renderReadmeTemplate(repositoryRoot *os.Root, fileName, packageRoot, buildPackageRoot, templatePath string, maskBundled bool, linksMap linkMap, schemaURLs fields.SchemaURLs) ([]byte, error) {
	logger.Debugf("Render %s file (package: %s, templatePath: %s)", fileName, packageRoot, templatePath)

	dataRoot := packageRoot
	if maskBundled || buildPackageRoot != "" {
		composable, err := hasRequiredInputs(packageRoot)
		if err != nil {
			return nil, fmt.Errorf("checking required inputs: %w", err)
		}
		maskBundled = maskBundled && composable
		if composable && buildPackageRoot != "" {
			dataRoot = buildPackageRoot
		}
	}

	t := template.New(fileName)
	t, err := t.Funcs(template.FuncMap{
		"event": func(args ...string) (string, error) {
			if len(args) > 0 {
				return renderSampleEvent(packageRoot, args[0])
			}
			return renderSampleEvent(packageRoot, "")
		},
		"fields": func(args ...string) (string, error) {
			if maskBundled {
				return bundledSentinel, nil
			}
			fieldsDir := filepath.Join(dataRoot, "fields")
			if len(args) > 0 {
				fieldsDir = filepath.Join(dataRoot, "data_stream", args[0], "fields")
			}
			// Always pass the source packageRoot so the validator can read _dev/build/build.yml
			// and resolve external ECS references.
			return renderExportedFields(repositoryRoot, packageRoot, fieldsDir, schemaURLs)
		},
		"url": func(args ...string) (string, error) {
			options := linkOptions{}
			if len(args) > 1 {
				options.caption = args[1]
			}
			return linksMap.RenderLink(args[0], options)
		},
		"inputDocs": func() (string, error) {
			if maskBundled {
				return bundledSentinel, nil
			}
			var inputTypes map[string]string
			if dataRoot != packageRoot {
				builtManifest, err := packages.ReadPackageManifestFromPackageRoot(dataRoot)
				if err != nil {
					return "", fmt.Errorf("reading built package manifest: %w", err)
				}
				inputTypes = inputTypesByName(builtManifest)
			}
			return renderInputDocs(dataRoot, inputTypes)
		},
		"ilm": func(args ...string) (string, error) {
			logger.Debug("renderILMPaths")
			return renderILMPaths(packageRoot, args)
		},
		"transform": func() (string, error) {
			logger.Debug("renderTransformPaths")
			return renderTransformPaths(repositoryRoot, packageRoot, schemaURLs)
		},
		"generatedHeader": func() string {
			return doNotModifyStr
		},
		"alertRuleTemplates": func() (string, error) {
			return renderAlertRuleTemplates(packageRoot, linksMap)
		},
		"sloTemplates": func() (string, error) {
			return renderSloTemplates(packageRoot, linksMap)
		},
	}).ParseFiles(templatePath)
	if err != nil {
		return nil, fmt.Errorf("parsing README template failed (path: %s): %w", templatePath, err)
	}

	var rendered bytes.Buffer
	err = t.Execute(&rendered, nil)
	if err != nil {
		return nil, fmt.Errorf("executing template failed: %w", err)
	}
	return rendered.Bytes(), nil
}

func readReadme(fileName, packageRoot string) ([]byte, bool, error) {
	logger.Debugf("Read existing %s file (package: %s)", fileName, packageRoot)

	readmePath := filepath.Join(packageRoot, "docs", fileName)
	b, err := os.ReadFile(readmePath)
	if err != nil && errors.Is(err, os.ErrNotExist) {
		return nil, false, nil
	}
	if err != nil {
		return nil, false, fmt.Errorf("readfile failed (path: %s): %w", readmePath, err)
	}
	return b, true, err
}

func writeReadme(fileName, packageRoot string, content []byte) (string, error) {
	logger.Debugf("Write %s file (package: %s)", fileName, packageRoot)

	docsPath := docsPath(packageRoot)
	logger.Debugf("Create directories: %s", docsPath)
	err := os.MkdirAll(docsPath, 0o755)
	if err != nil {
		return "", fmt.Errorf("mkdir failed (path: %s): %w", docsPath, err)
	}

	aReadmePath := readmePath(fileName, packageRoot)
	logger.Debugf("Write %s file to: %s", fileName, aReadmePath)

	err = os.WriteFile(aReadmePath, content, 0o644)
	if err != nil {
		return "", fmt.Errorf("writing file failed (path: %s): %w", aReadmePath, err)
	}
	return aReadmePath, nil
}

func readmePath(fileName, packageRoot string) string {
	return filepath.Join(docsPath(packageRoot), fileName)
}

func docsPath(packageRoot string) string {
	return filepath.Join(packageRoot, "docs")
}
