# An expected setting.
stack.geoip_dir: "/home/foo/Documents/ingest-geoip"
stack.logstash_enabled: true

# An empty string, should exist, but return empty.
other.empty: ""

# A nested value, should work as "other.nested".
other:
  nested: "foo"

# A number. Will be parsed as string.
other.number: 42

# A float. Will be parsed as string.
other.float: 0.12345

# A bool. Will be parsed as string.
other.bool: false
