FROM __BASE_IMAGE__
ARG PROFILE

# Disable package validation (already done).
ENV EPR_DISABLE_PACKAGE_VALIDATION=true

COPY profiles/${PROFILE}/stack/package-registry.config.yml /package-registry/config.yml
COPY stack/development/ /packages/development

ENTRYPOINT ["./package-registry", "-feature-proxy-mode"]