// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

package cmd

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/elastic/elastic-package/internal/cobraext"
	"github.com/elastic/elastic-package/internal/docs"
	"github.com/elastic/elastic-package/internal/packages"
)

const checkLongDescription = `Use this command to verify if the package is correct in terms of formatting, validation and building.

It will execute the lint and build commands all at once, in that order.

For packages that declare required input packages ("requires.input" in manifest.yml), the README is regenerated by the build with the content bundled from those packages, which lint can't verify. In this case the command fails, after building the package, if the regenerated README differs from the one that was committed, so that the changes can be reviewed and committed.`

func checkCommandAction(cmd *cobra.Command, args []string) error {
	packageRoot, err := packages.MustFindPackageRoot()
	if err != nil {
		return fmt.Errorf("package root not found: %w", err)
	}

	// The build regenerates the README of composable packages with the bundled content, that
	// can't be verified by lint. Keep the committed one to compare it with the regenerated one.
	readmes, err := docs.SnapshotComposableReadmes(packageRoot)
	if err != nil {
		return fmt.Errorf("checking package failed: %w", err)
	}

	err = cobraext.ComposeCommands(cmd, args,
		setupLintCommand(),
		setupBuildCommand(),
	)
	if err != nil {
		return fmt.Errorf("checking package failed: %w", err)
	}

	err = readmes.VerifyUnchanged()
	if err != nil {
		return fmt.Errorf("checking package failed: %w", err)
	}
	return nil
}

func setupCheckCommand() *cobraext.Command {
	cmd := &cobra.Command{
		Use:   "check",
		Short: "Check the package",
		Long:  checkLongDescription,
		Args:  cobra.NoArgs,
		RunE:  checkCommandAction,
	}
	cmd.PersistentFlags().BoolP(cobraext.FailFastFlagName, "f", true, cobraext.FailFastFlagDescription)

	return cobraext.NewCommand(cmd, cobraext.ContextPackage)
}
