#!/bin/bash

set -euo pipefail

if [[ "$BUILDKITE_PIPELINE_SLUG" == "elastic-package" && "$BUILDKITE_STEP_KEY" == "test-secret" ]]; then
  export MY_SECRET="foobar"
  export OTHER_VAR=${MY_SECRET}
  export FOO_VAR="something_${MY_SECRET}"
  export TEST_VAR="something_${OTHER_VAR}"
fi
