#!/bin/bash

source .buildkite/scripts/tooling.sh

set -euo pipefail

unset_secrets

# integrations-parallel-gcp
unset GOOGLE_CREDENTIALS
unset GCP_PROJECT_ID

# integrations-parallel-aws and intregrations-parallel-aws_logs
unset ELASTIC_PACKAGE_AWS_ACCESS_KEY
unset ELASTIC_PACKAGE_AWS_SECRET_KEY
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY

# cloud-cleanup
unset ELASTIC_PACKAGE_AWS_USER_SECRET
unset ELASTIC_PACKAGE_GCP_KEY_SECRET
unset ELASTIC_PACKAGE_GCP_EMAIL_SECRET
unset ELASTIC_PACKAGE_GCP_PROJECT_SECRET
