version: "3.5"
services:
  docker-custom-agent:
    image: "${ELASTIC_AGENT_IMAGE_REF}"
    healthcheck:
      test: "elastic-agent status"
      retries: 180
      interval: 1s
    hostname: docker-custom-agent
    environment:
      - FLEET_ENROLL=1
      - FLEET_URL=https://fleet-server:8220
      - KIBANA_HOST=https://kibana:5601
    volumes:
      - ${SERVICE_LOGS_DIR}:/tmp/service_logs/
      - ${LOCAL_CA_CERT}:/etc/ssl/certs/elastic-package.pem
    networks:
      - my-shared-network

# Network to communicate with the elastic stack
networks:
  my-shared-network:
    name: elastic_package_test_network
    external: true