---
name: Bump golangci-lint version
pipelineid: 'bump-golangci-lint-version'

actions:
  default:
    title: '[updatecli] Update golangci-lint to {{ source "latestVersion" }}'
    kind: github/pullrequest
    scmid: default
    spec:
      labels:
        - automation
        - dependency

scms:
  default:
    kind: github
    spec:
      owner: '{{ .scm.owner }}'
      repository: '{{ .scm.repository }}'
      user: '{{ requiredEnv "GITHUB_ACTOR" }}'
      username: '{{ requiredEnv "GITHUB_ACTOR" }}'
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      commitusingapi: true
      branch: main

sources:
  latestVersion:
    name: Get latest golangci-lint version
    kind: json
    spec:
      file: https://api.github.com/repos/golangci/golangci-lint/releases/latest
      key: .tag_name

targets:
  update-makefile:
    name: '[updatecli] Update golangci-lint to {{ source "latestVersion" }}'
    kind: file
    sourceid: latestVersion
    scmid: default
    spec:
      file: Makefile
      matchpattern: 'GOLANGCI_LINT_VERSION [?]= v[0-9.]+'
      replacepattern: 'GOLANGCI_LINT_VERSION ?= {{ source "latestVersion" }}'
