---
name: Update versions of Elastic Stack dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 1-5'

permissions:
  contents: read

jobs:
  bump-elastic-stack:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@v2.58.0 # v0.77.0

      - name: Run Updatecli in Apply mode
        # TODO: Change from diff to apply.
        # --experimental needed for commitusingapi option.
        run: updatecli --experimental apply --config .github/workflows/updatecli.d/bump-elastic-stack-version.yml --values .github/workflows/updatecli.d/scm.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ECOSYSTEM_USER_TOKEN }}
